#spring.application.name=restaurantlisting
spring:
  application:
    name: RESTAURANT-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
  profiles:
    active:
      - local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
server:
  port: 9091